"""Asserts that a bundle actually carries the runtime, the models and every notice.

Run after `tauri build`. Exits non-zero, loudly, if anything the release config
names is missing from what the bundler produced.

Why this exists
---------------

Round 3 of `I-337`'s independent review found the gap it closes, and the gap was
introduced by the fix for round 2's CI failure rather than by the original work.

The history in three steps, because the shape matters more than the bug:

1. `bundle.resources` lived in `tauri.conf.json`. Every build packaged the
   assets, structurally, because that file is read unconditionally. But
   `tauri-build` validates resource paths at COMPILE time, so every `cargo
   check` on a machine without the gitignored 47.6 MB staging directory failed.
2. The fix moved the resources into `tauri.release.conf.json`, merged in with
   `--config` only when an installer is built. That fixed the compile problem.
3. **It also made packaging depend on remembering a flag.** Exactly one line in
   `.github/workflows/ci.yml` supplies it. Drop it, typo it, or add a second
   release workflow that forgets it, and `tauri build` exits 0 and produces an
   installer with no runtime, no models and none of the three notices, with
   `cargo test`, `cargo clippy` and the whole CI run still green.

Step 3 is strictly worse than step 1's problem: a compile error is loud and
immediate, while shipping a GPL-3.0 installer that is missing an MIT licence it
is required to carry is silent and reaches users.

So this checks the ARTIFACT rather than the invocation. It does not care how the
build was run, which flags were passed, or which config was merged. It asks what
came out. That is the only form of the check that a future release workflow
nobody has written yet cannot route around.

What it checks
--------------

For every destination named in `tauri.release.conf.json`:

* the file is staged beside the built executable, where `ocr.rs` will look for
  it at run time;
* **every installer this build produced** carries a directive for it, so it
  travels to a user rather than merely existing in the build tree; and
* **its bytes hash to the digest pinned in `crates/uptake-assets/`**, at the
  source path the installers actually embed from.

The third check, and the gap it closes
--------------------------------------

`BACKLOG.md` **I-346**, raised as non-binding UNEASE by round 4 of `I-337`'s
review, which could not construct a divergence and said so.

The first two checks answer from two different directories that merely happen
to agree. Staging is checked in `target/release/`; both installers embed from
`src-tauri/assets/`, a separately populated copy. `acquire-onnxruntime.py`
verifies on acquisition and `src-tauri/src/ocr.rs` verifies on load, so the
digest is checked before the file is staged and again after it is installed,
and **the packaging step in between verified nothing.** Anyone who edited
`src-tauri/assets/` after running the acquisition script shipped those bytes.

So this hashes the source files, at the paths the release config gives the
bundler, against the pins already in the Rust source. Nothing is re-derived:
the digests are read out of `onnxruntime.rs` and `ppocr.rs` through
`scripts/rust_consts.py`, the same extraction `acquire-onnxruntime.py` uses, so
a rotated pin cannot be current in one place and stale in another.

**One resource is deliberately unpinned, and it is named rather than skipped.**
`models/NOTICE-models.txt` is generated by `write-model-notice.py` rather
than acquired, so there is no digest to hold it to. A checker that quietly
passed over anything it had no pin for would be the false green this whole file
exists to refuse, so an unpinned resource has to be listed by name in
`UNPINNED` below and is reported as UNVERIFIED in the output. A resource that
is neither pinned nor listed is a refusal.

The second check is the load-bearing one. A stale file from an earlier build
satisfies the first on its own, which is precisely the false green this is
supposed to refuse.

**"Every installer" is plural on purpose.** `bundle.targets` is `"all"`, so a
Windows build emits an NSIS setup and an MSI and CI uploads both. Round 4 of
this change's review found the first version of this file reading the NSIS
script alone and reporting success over an MSI that carried nothing.

Usage
-----

    python scripts/verify-bundle.py
    python scripts/verify-bundle.py --target target/release
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

# Sibling module. Both this script and its tests run as `python scripts/<name>.py`
# from the repository root, which puts `scripts/` on `sys.path` as the script's
# own directory.
import rust_consts

REPO = Path(__file__).resolve().parent.parent

#: The release-only config whose `bundle.resources` map is the authority on what
#: an installer must carry. Read rather than restated, so this cannot drift from
#: the file the bundler is given.
RELEASE_CONFIG = REPO / "src-tauri" / "tauri.release.conf.json"


#: Where each pinned digest lives, as (Rust file, constant name), keyed by the
#: SOURCE path the release config hands the bundler.
#:
#: Keyed by source rather than by destination on purpose: the source is the file
#: whose bytes get embedded, and it is the one thing the other two checks never
#: look at. The destination is the same string with `assets/` stripped today,
#: and writing the mapping against it would make that coincidence load-bearing.
PINNED = {
    "assets/onnxruntime.dll": ("onnxruntime.rs", "RUNTIME_SHA256"),
    "assets/LICENSE-onnxruntime.txt": ("onnxruntime.rs", "LICENCE_SHA256"),
    "assets/ThirdPartyNotices-onnxruntime.txt": ("onnxruntime.rs", "NOTICES_SHA256"),
    # ADR-0036: Baidu's own ONNX, downloaded rather than converted. The pin
    # is read from the same constant either way, so this table did not have to
    # learn the difference -- only the file name moved.
    "assets/models/PP-OCRv6_small_det.onnx": ("ppocr.rs", "DETECTION_SHA256"),
    "assets/models/PP-OCRv6_small_rec.onnx": ("ppocr.rs", "RECOGNITION_SHA256"),
    "assets/models/ppocr_keys_v6_small.txt": ("ppocr.rs", "DICTIONARY_SHA256"),
}

#: Resources that have no pin, and why. Listed rather than skipped: see the
#: header. Each entry is a source path mapped to the reason, which is printed.
UNPINNED = {
    "assets/models/NOTICE-models.txt": (
        "generated by scripts/write-model-notice.py from the pins, and its own"
        " licences, so there is no upstream digest to hold it to"
    ),
}

#: Where the pins are read from.
PINS_DIRECTORY = REPO / "crates" / "uptake-assets" / "src"


def digest_of_file(path: Path) -> str:
    """The SHA-256 of `path`, lowercase hex, read in chunks.

    Chunked because the runtime DLL is 16 MB and the recogniser 10 MB, and
    there is no reason for a checker to hold either in memory whole.
    """
    hasher = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            hasher.update(chunk)
    return hasher.hexdigest()


def pinned_digests() -> dict[str, str]:
    """Every pinned digest, by the source path it belongs to.

    Raises `SystemExit` if any named constant cannot be read. A checker that
    carries on with a partial mapping would report success over the resources
    whose pins it happened to find, which is the same false green one level
    down.
    """
    sources: dict[str, str] = {}
    digests: dict[str, str] = {}
    for source_path, (rust_file, constant) in PINNED.items():
        if rust_file not in sources:
            path = PINS_DIRECTORY / rust_file
            if not path.is_file():
                raise SystemExit("cannot find the pins at " + str(path))
            sources[rust_file] = path.read_text(encoding="utf-8")
        value = rust_consts.string_const(sources[rust_file], constant)
        if value is None:
            raise SystemExit(
                "could not find `pub const "
                + constant
                + ": &str` in "
                + str(PINS_DIRECTORY / rust_file)
                + ".\nThe pins moved and this script cannot read them. Fix the"
                " extraction rather than copying the value here."
            )
        digests[source_path] = value
    return digests


def byte_problems(config_path: Path, resources: dict[str, str]) -> tuple[list[str], list[str]]:
    """Refusal reasons for the source bytes, plus the unverified resources.

    `resources` is the release config's `bundle.resources` map, source path to
    destination, so this walks exactly what the bundler is given rather than a
    restatement of it.
    """
    digests = pinned_digests()
    problems: list[str] = []
    unverified: list[str] = []
    for source_path in sorted(resources):
        absolute = (config_path.parent / source_path).resolve()
        if source_path in UNPINNED:
            unverified.append(source_path + " (" + UNPINNED[source_path] + ")")
            continue
        if source_path not in digests:
            problems.append(
                source_path
                + " is neither pinned in PINNED nor listed in UNPINNED, so its"
                " bytes are unchecked and nothing here says that was intended."
                "\n    Add it to one of the two in scripts/verify-bundle.py."
            )
            continue
        if not absolute.is_file():
            problems.append(
                source_path
                + " is named by the release config but is not on disk at "
                + str(absolute)
                + " (run the acquisition and conversion scripts)"
            )
            continue
        actual = digest_of_file(absolute)
        if actual != digests[source_path]:
            problems.append(
                source_path
                + " does NOT match its pinned digest.\n    expected "
                + digests[source_path]
                + "\n    found    "
                + actual
                + "\n    "
                + str(absolute)
                + "\n    These are the bytes an installer would embed. Re-run"
                " the acquisition or conversion script rather than rotating the"
                " pin, unless the pin is what changed."
            )
    return problems, unverified


def resource_map(config_path: Path) -> dict[str, str]:
    """The release config's `bundle.resources`, source path to destination.

    Raises `SystemExit` rather than returning an empty map if it is missing or
    empty: a checker that silently finds nothing to check is the green that
    cannot be earned, which is the defect this whole file is about.

    Both the destination checks and the byte check read this ONE call, so they
    cannot end up walking different resource lists.
    """
    if not config_path.is_file():
        raise SystemExit("cannot find the release config at " + str(config_path))
    config = json.loads(config_path.read_text(encoding="utf-8"))
    resources = config.get("bundle", {}).get("resources")
    if not resources:
        raise SystemExit(
            str(config_path)
            + " names no bundle.resources.\nThere is nothing for an installer to"
            " carry, which means the runtime, the models and every notice would"
            " ship missing. Refusing to report success."
        )
    return {str(source): str(destination) for source, destination in resources.items()}


def expected_destinations(config_path: Path) -> list[str]:
    """The installed paths the release config promises, relative to the exe."""
    resources = resource_map(config_path)
    return sorted(str(destination) for destination in resources.values())


def installer_manifests(target: Path) -> tuple[list[tuple[str, Path]], list[str]]:
    """Every installer script this build produced, and any reason to refuse.

    **Both of them, and that is the whole of round 4's finding.**
    `tauri.conf.json` sets `bundle.targets` to `"all"`, so a Windows build emits
    an NSIS setup **and** an MSI, and `ci.yml` uploads both as release
    artifacts. The first version of this file read the NSIS script only and
    reported "the bundle carries every resource" while the MSI beside it carried
    none: drilled by the reviewer, who stripped the resource components out of a
    real generated `main.wxs` and watched this script exit 0.

    A checker that says "the bundle" while inspecting one of two shipped
    bundles is the false green this file exists to refuse, one level up.

    Returns the manifests found, plus refusal reasons for anything ambiguous. A
    duplicate architecture directory is a refusal rather than a guess: the
    previous version took `sorted(...)[0]`, which silently prefers whichever
    name sorts first rather than whichever build is current.
    """
    found: list[tuple[str, Path]] = []
    problems: list[str] = []
    for label, pattern in (("NSIS", "nsis/*/installer.nsi"), ("MSI", "wix/*/main.wxs")):
        matches = sorted(target.glob(pattern))
        if len(matches) > 1:
            problems.append(
                label
                + " has more than one generated script ("
                + ", ".join(str(m) for m in matches)
                + "), so there is no single artifact to check. Clean the target"
                " directory and rebuild rather than letting this guess."
            )
            continue
        if matches:
            found.append((label, matches[0]))
    return found, problems


def embeds(label: str, manifest: str, destination: str) -> bool:
    r"""Whether `manifest` carries a directive that installs `destination`.

    The two generators say it differently and neither is a substring of the
    other, so this is a per-format question rather than one shared search:

    * NSIS writes the INSTALLED path, as `/oname=models\ppocr_keys_v1.txt`.
    * WiX writes the SOURCE path, as
      `<File ... Source="...\src-tauri\assets\models\ppocr_keys_v1.txt" />`.

    Matching the source path for WiX is what makes the check meaningful there:
    the staging layout under `src-tauri/assets` mirrors the installed layout, so
    a resource that is present under one name and absent under the other cannot
    satisfy both this and the staging check.
    """
    windows = destination.replace("/", "\\")
    if label == "NSIS":
        return "/oname=" + windows in manifest
    return "assets\\" + windows in manifest


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--target",
        type=Path,
        default=REPO / "target" / "release",
        help="the build output directory (default: target/release)",
    )
    arguments = parser.parse_args()
    target: Path = arguments.target

    resources = resource_map(RELEASE_CONFIG)
    destinations = sorted(resources.values())
    print("Checking " + str(len(destinations)) + " bundled resource(s) in " + str(target))

    if not target.is_dir():
        raise SystemExit(
            str(target) + " does not exist. Build first, then run this."
        )

    problems: list[str] = []

    # 0. The bytes an installer would embed, against the pins in the Rust
    #    source (I-346). First, because it is the only check that looks at the
    #    directory the installers actually read from, and a digest mismatch
    #    there makes the other two green over the wrong file.
    byte_refusals, unverified = byte_problems(RELEASE_CONFIG, resources)
    problems.extend(byte_refusals)

    # 1. Staged beside the executable, which is where `ocr.rs` resolves them.
    for destination in destinations:
        staged = target / destination
        if not staged.is_file():
            problems.append(
                destination
                + " is NOT staged beside the executable (looked for "
                + str(staged)
                + ")"
            )

    # 2. Actually referenced by the installer the bundler generated. This is the
    #    check that catches a build run without the release config: the staging
    #    directory can be populated by a previous build while the installer that
    #    was just produced carries nothing.
    manifests, ambiguities = installer_manifests(target)
    problems.extend(ambiguities)
    if not manifests:
        problems.append(
            "no generated installer script found under "
            + str(target)
            + " (looked for nsis/*/installer.nsi and wix/*/main.wxs); either no"
            " bundle was produced or the target is wrong"
        )
    for label, script in manifests:
        directives = script.read_text(encoding="utf-8", errors="replace")
        for destination in destinations:
            if not embeds(label, directives, destination):
                problems.append(
                    destination
                    + " is NOT in the "
                    + label
                    + " installer ("
                    + str(script)
                    + " has no directive for it)"
                )

    if problems:
        print("")
        print("REFUSED. The bundle does not carry what the release config promises:")
        for problem in problems:
            print("  - " + problem)
        print("")
        # The guidance is per KIND of failure, and it was not until I-346 added a
        # second kind. A digest mismatch printed under "the usual cause is a
        # build run without --config" sends the reader to check a flag that is
        # not the problem, which is a checker going red and pointing the wrong
        # way -- barely better than not firing.
        if byte_refusals:
            print(
                "A digest mismatch is NOT a flag problem. Those bytes are what"
                " an installer would embed, and they are not the bytes this"
                " repository pins. Re-run scripts/acquire-onnxruntime.py or"
                " scripts/write-model-notice.py, and rotate a pin only if the"
                " pin is what you meant to change."
            )
        if len(problems) > len(byte_refusals):
            print(
                "The usual cause of a MISSING resource is a build run without"
                " `--config src-tauri/tauri.release.conf.json`, which exits 0 and"
                " produces an installer with no runtime, no models and no notices."
            )
        print(
            "Shipping that installer would violate ONNX Runtime's MIT notice"
            " requirement and PaddleOCR's Apache-2.0 one, and `cargo deny` cannot"
            " see either, because it walks the crate graph."
        )
        return 1

    for destination in destinations:
        print("  ok  " + destination)
    print("")
    print(
        "Every resource the release config names is staged and carried by: "
        + ", ".join(label for label, _ in manifests)
        + "."
    )
    # Both halves, always, and on the SUCCESS path deliberately: the point of
    # naming an unpinned resource is that a reader of a GREEN run learns what
    # was not checked, and saying it only on failure would be saying it to
    # nobody. Two separate sentences rather than one branch, because "these
    # hashed correctly" and "these were not hashed at all" are both true at
    # once and an `else` would print only one of them.
    print(
        str(len(resources) - len(unverified))
        + " of them hashed to the digest pinned in crates/uptake-assets/."
    )
    if unverified:
        print("")
        print("Bytes NOT verified, by name (no pin exists for these):")
        for entry in unverified:
            print("  --  " + entry)
    return 0


if __name__ == "__main__":
    sys.exit(main())
